name: flutter_riverpod_todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.7
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  riverpod: ^3.0.3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
